expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
      notarySecretName: harbor-tls
  ingress:
    hosts:
      core: harbor.lmsx.io.vn
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

externalURL: https://harbor.lmsx.io.vn

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 20Gi
    database:
      size: 5Gi
    redis:
      size: 1Gi

harborAdminPassword: "Harbor12345"

# Disable Trivy nếu không cần
trivy:
  enabled: true

# Disable Notary nếu không cần
notary:
  enabled: true

# Database internal
database:
  type: internal

# Redis internal  
redis:
  type: internal
