---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-manager-storage
  namespace: cert-manager
  labels:
    app: cert-manager
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cstor-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-manager-backup
  namespace: cert-manager
  labels:
    app: cert-manager
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cstor-sc
  resources:
    requests:
      storage: 10Gi
